"""add parent_id to transactions

Revision ID: d1546b6558e3
Revises: 6926ae852392
Create Date: 2026-02-27 21:10:34.913224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1546b6558e3'
down_revision: Union[str, None] = '6926ae852392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_transactions_parent_id_transactions'), 'transactions', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_parent_id_transactions'), type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
