"""add merge_parent_id to transactions

Revision ID: e675c8da2a60
Revises: d1546b6558e3
Create Date: 2026-02-28 22:06:16.850196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e675c8da2a60'
down_revision: Union[str, None] = 'd1546b6558e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merge_parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_transactions_merge_parent_id_transactions'), 'transactions', ['merge_parent_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_merge_parent_id_transactions'), type_='foreignkey')
        batch_op.drop_column('merge_parent_id')

    # ### end Alembic commands ###
